### ISSUE TITLE
Contextual help possible?

### ISSUE THREAD

**Issue by edannenberg** [matejak/argbash#1]
Hello, I'm currently looking for a clean way to get contextual help in a bash project of mine and stumbled across `argbash`. Except for the lack of short argument clustering, which I can probably live with, it looks very promising. However after reading the docs and playing around a bit I'm not sure `argbash` is a good fit for contextual help. The pattern is fairly common now in modern cli applications like git or docker:

```
# print main help, global options like --verbose and main commands  with short description
./mainscript 
# print help text for command, global options and options specific to this command
./mainscript <command> --help
```

I pretty much have no idea what I'm doing yet, but it looks like I would need a conditional `# INCLUDE_PARSING_CODE([cmd-foo-parsing.sh])` instruction to get the desired behaviour. Maybe I'm missing something obvious here. Could you provide a rough example if this is possible or what the best approach for this would be using `argbash`?

Ideally I would like to separate the parsing code completely and just regenerate some parsing templates occasionally when new commands/options are added.

Thanks!

**Comment by matejak** [comment]
The feature you mention is referred to as "subparsers". Well-known utility that uses this functionality is, for example, `git`.
`Atgbash` doesn't support subparsers, and although it is theoretically possible, I don't think it will.
However, you can use a workaround. If we consider a script that mimics `git`, it would be a script that accepts one positional argument (the operation, e.g. `pull`, `commit` etc.), leftover arguments (arguments to subcommands) and some generic optional arguments (help, version).
The `git` script would then parse the command-line and decide (according to the positional argument) what to call: `git-pull`, `git-commit` or another standalone script.
The contents of `"${_arg_leftovers[@]}"` would be supplied as arguments - see `ARG_LEFTOVERS` reference at http://argbash.readthedocs.io/en/latest/guide.html
Although this is a slight workaround, it should be usr-friendly. You don't have to use advanced `Argbash` functionality s.a. script wrapping or parsing code in separate file, you just have to have the main script (`git`) and the specialized scripts (`git-pull`, `git-commit` etc.).
It is great that you are interested in the `Argbash`, I hope that it will keep benefiting you from now on!

**Comment by edannenberg** [comment]
Yea that would work, the only downside to this approach is that I would have to duplicate the global options in each command script, which is what I was trying to avoid. `INCLUDE_PARSING_CODE` looked very nice in that regard. But it's not a big issue as there are not that many global options in my case. 

Thanks for the answer and for making bash scripting a bit less painful!

**Comment by matejak** [comment]
If inheritance is what you want, you should be able to use `ARGBASH_WRAP` macro. You just wrap the the global definitions, they will propagate to the script that includes the directive.

**Comment by edannenberg** [comment]
Yes, actually I meant to talk about `ARGBASH_WRAP` the whole time, my bad. Got a bit further last night, this is my current setup:

```
/some-app
|-- argbash/
  |-- foo.sh
  |-- bar.sh
  |-- opt-global.sh
  .-- opt-main.sh
|-- cmd/
  |-- foo.sh
  .-- bar.sh
.-- main.sh
```

`argbash/opt-global.sh`:
```bash
# ARG_VERSION([echo $0 ${app_version}])
# ARG_OPTIONAL_BOOLEAN(verbose)
# ARGBASH_GO
```

`argbash/opt-main.sh`:
```bash
# ARG_POSITIONAL_SINGLE([command], [command to run], )
# ARGBASH_WRAP([opt-global])
# ARG_LEFTOVERS([command-opt])
# ARG_HELP([some app])
# ARGBASH_GO
```

`argbash/{foo,bar}.sh`:
```bash
# ARG_POSITIONAL_SINGLE([some-opt],[description],[])
# ARGBASH_WRAP([opt-global])
# ARG_LEFTOVERS([command-opt])
# ARG_HELP([some app - command help])
# ARGBASH_GO()
```

`main.sh`:
```bash
arg_script="${script_dir}/argbash/opt-main.sh"
test -f "$arg_script" && source $arg_script || { echo "Missing the wrapped script, was expecting it next to me, in '$script_dir'."; exit 1; }

cmd_script="${script_dir}/cmd/${_arg_command}.sh"
test -f "${cmd_script}" && source "${cmd_script}" "${_arg_leftovers[@]}" || die "error, unknown <command>"
```

The `cmd` scripts just source their counterpart in `argbash` dir.

Works and is almost what I had in mind, except `./main.sh foo --help` will show the main help and not the command's help, not sure how to resolve that other then not using argbash for the main script. Any ideas?

I'm also not 100% sure on how to use `ARG_LEFTOVERS`, I got the gist I think but no idea what the actual values should be. The `command-opt` as I used it in `ARG_LEFTOVERS([command-opt])` would make it seem that any random string will do? :thinking:

One nice-to-have for my use case would be some sort of optional `ARGBASH_HELP_HEADER` I could define in `opt-global.sh` to be reused in all other parsers, which is displayed before the actual `ARGBASH_HELP`.

**Comment by edannenberg** [comment]
Another issue I didn't notice before, as `foo.sh` has a required positional `some-opt`, `./main.sh foo` should throw a missing req. argument error but instead the command `foo` is parsed as `$_arg_some_opt`.

**Comment by edannenberg** [comment]
Think I got it now, I had to remove `ARG_LEFTOVERS` from `argbash/{foo,bar}.sh`, which I prev. added only because without it `./main.sh foo bazbaz` would complain about too many arguments. Apparently not a proper solution to the problem as it caused the issue from my prev. comment. :laughing:

After looking at the generated `argbash/foo.sh` parsing code it became clear that I had to reset `$_positionals` manually in `main.sh` before including any command script. I updated the example code above.

Everything seems to be in order now except for `./main foo --help` displaying the main help. I think this could be handled if `argbash` provided an option (macro?) to disable automatic help display in the generated parsing code if `--help` is passed. If the option is enabled, instead of displaying the help text, the generated parsing code should just define a `$_arg_help` boolean or similiar and leave handling of the `--help` option to the script. For the example above it would then be enough to simply add:

```bash
[ -z $_arg_command ] && [ $_arg_help -eq "on" ] && print_help && exit 0
```

..to `main.sh`.

**Comment by edannenberg** [comment]
Except for a few teething issues I fully migrated to Argbash now. Very happy with the outcome. Thanks for this much needed project!

I created a [subparsers example](https://github.com/edannenberg/argbash/tree/subparsers/resources/examples) which I plan to submit as PR if you are interested. Just needs a bit more docs.

**Comment by edannenberg** [comment]
I think this can be closed, the minor issues left have separate issues by now. For the time being I manually have to massage the generated argbash code a bit to get the desired output.

**Comment by DryHumorInDC** [comment]
> The feature you mention is referred to as "subparsers". Well-known utility that uses this functionality is, for example, `git`. `Atgbash` doesn't support subparsers, and although it is theoretically possible, I don't think it will. However, you can use a workaround. If we consider a script that mimics `git`, it would be a script that accepts one positional argument (the operation, e.g. `pull`, `commit` etc.), leftover arguments (arguments to subcommands) and some generic optional arguments (help, version). The `git` script would then parse the command-line and decide (according to the positional argument) what to call: `git-pull`, `git-commit` or another standalone script. The contents of `"${_arg_leftovers[@]}"` would be supplied as arguments - see `ARG_LEFTOVERS` reference at http://argbash.readthedocs.io/en/latest/guide.html Although this is a slight workaround, it should be usr-friendly. You don't have to use advanced `Argbash` functionality s.a. script wrapping or parsing code in separate file, you just have to have the main script (`git`) and the specialized scripts (`git-pull`, `git-commit` etc.). It is great that you are interested in the `Argbash`, I hope that it will keep benefiting you from now on!

I see how this would work for passing arguments to the subcommand, but is there also a way to have the bash completion work for subcommands?
