### ISSUE TITLE
howto argbash-init posix-script

### ISSUE THREAD

**Issue by rubicks** [matejak/argbash#103]
Am I doing something wrong or expecting too much?

```
$ ~/.local/bin/argbash-init --opt o - | ~/.local/bin/argbash -t posix-script -
stdin:38: error: Optional arguments '--o' don't have a short option, which is not supported in POSIX mode.
stdin:38: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
Error during autom4te run, aborting!
```

**Comment by matejak** [comment]
Argbash POSIX output allows only optional arguments with short options, which `argbash-init` doesn't support - you can't specify short options - you have to edit the template to specify short options.
So to answer the question - you are not doing anything wrong, `argbash-init` can't produce the POSIX template.
Now when this is known, let's think what would make it more understandable to you?

**Comment by rubicks** [comment]
@matejak I think understand completely that what I'm trying to do is unsupported by `argbash-init` in its current form. And that's fine by me; I can make my own templates with a little bit of hacker. Thanks for your help!
