### ISSUE TITLE
argbash-init - generates template file OK, but shows a chmod error

### ISSUE THREAD

**Issue by PushEngineering** [matejak/argbash#107]
Running on MacOS Mojave (10.14.6), installed argbash 2.8.1 to `$HOME/.local/bin`

Running some basic argbash-init tests & get the following sort of error when specifying the output filename...

```
$ argbash-init --pos tables --opt stack-id --hints dump-db-to-s3.m4
chmod: --: No such file or directory
```

The template file `dump-db-to-s3.m4` is generated OK tho. Not specifying the output file, prints the output to STDOUT & there is no chmod error.

**Comment by matejak** [comment]
It looks like that the MacOS `chmod` doesn't recognize the `--` string as the terminator and thinks that it is a file. Shame on them!
However, it seems to be safe to remove it without any noticeable implications.
