### ISSUE TITLE
DEFINE_VALUE_TYPE_FILE doesn't work at all

### ISSUE THREAD

**Issue by impredicative** [matejak/argbash#118]
I tried the following (excerpted) with the online generator:

```bash
# ARG_POSITIONAL_SINGLE([in],[Path to input file])
# ARG_POSITIONAL_SINGLE([out],[Path to output file])
# DEFINE_VALUE_TYPE_FILE([in], [r], [input CSV file], [in])
# DEFINE_VALUE_TYPE_FILE([out], [w], [output CSV file], [out])
# ARGBASH_GO()
```

`DEFINE_VALUE_TYPE_FILE` produced no code at all and it does nothing. If it's not implemented, it should at least get undocumented.

**Comment by felipecassiors** [comment]
I think it's not available yet.

> Warning
>
> Features described in this section are experimental. Macros in the type-related section below are > not an official part of the API yet — their names and/or signature may change.
>
> The documentation here is just a peek into the Argbash future. Please raise an issue if you feel > you can provide helpful feedback!

**Comment by impredicative** [comment]
That is so very strange. It is extremely weird and misleading to document features that don't exist, even if it comes with the warning. It's not what documentation is supposed to be about. Why not remove the whole section, and document what's actually implemented and supported?

**Comment by matejak** [comment]
Thanks for the report, both of you are correct - it is not implemented, and it is extremely misleading that it is documented. I will evaluate whether it can be fixed by implementing the feature, or it is wiser to remove it from the documentation.
