### ISSUE TITLE
New convenience function: load library

### ISSUE THREAD

**Issue by felipecassiors** [matejak/argbash#119]
This function is supposed to load a library file (`source lib.sh`) relative to the script's current folder and properly deal with the errors, such as not being able to find the library file.

Something like this:

```bash
function load_lib() {
  local lib_file=$1
  # shellcheck disable=SC1090
  source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$lib_file" || die "[ERROR] Not able to load the library $lib_file"
}

laod_lib "../common.sh"
load_lib "lib.sh"
```

With the template:

```sh
# DEFINE_LOAD_LIB
```

**Comment by matejak** [comment]
Thanks for the suggestion, I will look into it.
