### ISSUE TITLE
ARG_VERSION / ARG_VERSION_AUTO should use -V instead of -v flag

### ISSUE THREAD

**Issue by farmergreg** [matejak/argbash#123]
I think that -v for version should be changed to -V for the ARG_VERSION macros, or alternatively, no short form should be specified by the macros so that -v is left for the program to use if it needs to.

-v is commonly used to ask for more verbose output in many programs (e.g. ssh -v)
-V is often used (e.g. ssh -V) to print version information

thanks for argbash, I've gotten a ton of benefit out of it and I only discovered it a few days ago.

**Comment by matejak** [comment]
This is quite subjective, as e.g. https://tldp.org/LDP/abs/html/standard-options.html specifies that `-v` is ambiguously good for version an verbose. I guess that the easiest way is to make `ARG_VERSION` configurable in the similar way as `ARG_HELP`.
