### ISSUE TITLE
recursion: parse arguments from file

### ISSUE THREAD

**Issue by milahu** [matejak/argbash#158]
gcc has this option:

> `@file`
> 
> Read command-line options from file. The options read are inserted in place of the original `@file` option. If file does not exist, or cannot be read, then the option will be treated literally, and not removed.
> 
> Options in file are separated by whitespace. A whitespace character may be included in an option by surrounding the entire option in either single or double quotes. Any character (including a backslash) may be included by prefixing the character to be included with a backslash. The file may itself contain additional `@file` options; any such options will be processed recursively.
>
> ([gcc/Overall-Options.html](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html))

so the `@my-args.txt` argument is expanded / replaced with the contents of the `my-args.txt` file

my use case: i made my own parser generator, generated from [gcc's opt files](https://github.com/gcc-mirror/gcc/blob/master/gcc/common.opt), to parse a subset of gcc options in [gcc-options-parser](https://github.com/milahu/gcc-options-parser) ... now im looking for a cheap way to implement the "parse arguments from file" feature

challenge: string parsing &rarr; [shlex](https://docs.python.org/3/library/shlex.html) in python

cheap solution: eval

```sh
#! /usr/bin/env bash

args=("$@")
argsLen=${#args[@]}
argsParsed=()
for (( i=0; i<$argsLen; i++ ))
do
  a="${args[$i]}"
  case "$a" in
    @*)
      argsFile="${a:1}"
      [ ! -e "$argsFile" ] && { echo "error parsing option $a: no such file"; exit 1; }
      eval fileArgs=( $(cat "$argsFile") ) # WARNING eval is unsafe
      args=( "${args[@]:0:$i}" "${fileArgs[@]}" "${args[@]:$((i + 1))}" ) # replace the @file argument
      argsLen=${#args[@]} # update length
      : $((i--)) # re-parse the replaced argument
    ;;
    *)
      argsParsed+=("$a")
    ;;
  esac
done

for (( i=0; i<${#argsParsed[@]}; i++ ))
do
  echo "$i: ${argsParsed[$i]}"
done

```

**Comment by matejak** [comment]
This is slightly beyond the scope of Argbash, although if the feature was cheap, it would make sense. Having an eval that executes contents of a runtime-supplied file is too much.
