### ISSUE TITLE
Parity with docopt

### ISSUE THREAD

**Issue by btamayo** [matejak/argbash#18]
I was wondering if argbash has any future plans to have parity with http://docopt.org/ in terms of help and usage formatting (not necessarily API/templating), provided that docopt is POSIX-compliant? 

Right now, docopt has python dependencies, and has no pure bash implementation.

**Comment by matejak** [comment]
This is a cool utility that I have completely missed. Thank you for pointing it out, I will examine it and analyze its relation to Argbash.
A quick look at it tells me that it is both meaningful and relatively easy to make Argbash usage messages docopt-compliant.

**Comment by btamayo** [comment]
If it's helpful to you, perhaps you can add it under 'resources' in your docs too. :)

**Comment by matejak** [comment]
Yes, I will do it as soon as time constraints allow it.

**Comment by matejak** [comment]
As Argbash supports docopt output, the work left in this issue is mainly about documenting docopt in appropriate places in the documentation. A cool feature would be a docopt-to-argbash converter.

**Comment by matejak** [comment]
Documentation has been added, so I close this issue.
