### ISSUE TITLE
Example with combined shorthand for flags

### ISSUE THREAD

**Issue by btamayo** [matejak/argbash#19]
I would like to see please an example with the following type of options, where the short bool options (flags) can be combined into a single option:

### Example:

Simple:
```shell
$ tar -xvzf tarfile.tar.gz
```

Where the options `-x`, `-v`, `-z`, `-f` are combined. 

Slightly more complex:
```shell
$ tar -rv -f abc.tar abc.txt
```

Flags combined + case sensitive argument (`-C`) + positional (filename "abc.tar.gz"):

```shell
$ tar -xvzf abc.tar.gz -C /opt/folder/
```

Examples from: http://www.binarytides.com/linux-tar-command/

At the moment, I'm not sure how much support argbash templates and API have for these flags.

**Comment by matejak** [comment]
Hello, argbash supports this functionality by default. The only thing you need is to declare multiple optional arguments with short options.
I was not able to find name of this behavior, so now it is being referred to as (short) option grouping.

**Comment by matejak** [comment]
Can I close this as resolved, or did you have an actual example in your mind?

**Comment by btamayo** [comment]
@matejak Hi! Yes, sorry. :) I understand you, would be great if that were a bit clearer in the docs.

**Comment by matejak** [comment]
See the `ARG_OPTION_STACKING` macro documented at https://argbash.readthedocs.io/en/latest/guide.html#convenience-macros
If you think that the documentation is insufficient, feel free to suggest improvements and reopen the issue.
