### ISSUE TITLE
instructions for make install are wrong

### ISSUE THREAD

**Issue by jmahowald** [matejak/argbash#21]
The instructions indicate that you should run

`make install PREFIX=/usr/bin` to get argbash installed system wide.  But that puts it in /usr/bin/bin/argbash. 

to do it and get the expected behavior, it should either read `make install PREFIX=/usr` or update the Makefile

**Comment by matejak** [comment]
Hello, thank you for using Argbash and for your time you have used to make the report! However, I need more help concerning the message - where have you picked it?
The documentation at http://argbash.readthedocs.io/en/latest/install.html suggests using `sudo make install PREFIX=/usr`, so my guess is that you must have stumbled upon a wrong or misleading instruction somewhere else.

**Comment by jmahowald** [comment]
Thank you for making argbash.  It’s totally changed my thinking on the cost of using bash to build good cli tools

https://github.com/matejak/argbash/blame/master/README.md#L20 <https://github.com/matejak/argbash/blame/master/README.md#L20>

**Comment by matejak** [comment]
Great, thank you for pointing this out! I have fixed the README in the master branch.
