### ISSUE TITLE
[RFE] Bash completion generator

### ISSUE THREAD

**Issue by sgallagher** [matejak/argbash#29]
It would be fantastic if argbash could generate a framework for a bash-completion script that matches the arguments it accepts.

**Comment by matejak** [comment]
You are right, it is in the long-term plan.

**Comment by matejak** [comment]
The preview of a bash completion generator will be present in the upcoming release.

**Comment by matejak** [comment]
The bash completion needs checking, `complete -F _argbash_sh argbash.sh` should be `complete -F _argbash_sh argbash`

**Comment by matejak** [comment]
Basically resolved by #52
