### ISSUE TITLE
Silently fails if bash is invoked with -e

### ISSUE THREAD

**Issue by ledettwy** [matejak/argbash#30]
Invoking a script generated by `argbash` with -e set (either with `set -e` at the top or running it with `bash -e`) will make `handle_passed_args_count` fail silently with error code 1, since I guess the `test` command actually fails by design (returns 1) if all the correct arguments are supplied.

**Comment by matejak** [comment]
Good catch, it will be fixed in the next bugfix release that is around the corner.
