### ISSUE TITLE
Handle shellcheck issues of generated script

### ISSUE THREAD

**Issue by rugk** [matejak/argbash#32]
Using the "optional & pos." online example and pasting that into [shellcheck](https://www.shellcheck.net/) shows many issues:

``` 
$ shellcheck myscript
 
Line 59:
        printf "%s\n" "The general script's help msg"
                  ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
 
Line 61:
        printf "\t%s\n" "<positional-arg>: positional argument help  msg"
                ^-- SC1117: Backslash is literal in "\t". Prefer explicit escaping: "\\t".
                    ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
 
Line 62:
        printf "\t%s\n" "-o,--option: optional argument help msg (no default)"
                ^-- SC1117: Backslash is literal in "\t". Prefer explicit escaping: "\\t".
                    ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
 
Line 63:
        printf "\t%s\n" "--print,--no-print: boolean optional argument help msg (off by default)"
                ^-- SC1117: Backslash is literal in "\t". Prefer explicit escaping: "\\t".
                    ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
 
Line 64:
        printf "\t%s\n" "-h,--help: Prints help"
                ^-- SC1117: Backslash is literal in "\t". Prefer explicit escaping: "\\t".
                    ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
 
Line 162:
echo "Value of positional-arg: $_arg_positional_arg"
                               ^-- SC2154: _arg_positional_arg is referenced but not assigned.

$ 
```

Please let all shellcheck tests pass…

**Comment by matejak** [comment]
As of now, shellcheck checks are part of the tests. However, to make them pass, there is an error ignore list: https://github.com/matejak/argbash/blob/restruct/resources/Makefile#L4

Those are minor issues - SC2015 is a non-issue, and the other three are related to test cases when argbash generates a bash module with parsing code. Therefore, I think that this issue can be closed, although I would like shellcheck to be able to find sourced files during the tests. Any ideas how to accomplish that?

**Comment by edannenberg** [comment]
See Shellcheck [directives](https://github.com/koalaman/shellcheck/wiki/Directive):

`# shellcheck source=foo/bar.sh`

If the include is truly dynamic you are out of luck AFAIK.

**Comment by rugk** [comment]
Indeed that's the correct way. You also need to run shellsheck with the `-x` parameter.

**Comment by matejak** [comment]
Well, it was not a low-hanging fruit, but now argbash scripts and tests are checked by shellcheck and only non-issues get the exception. Hooray!
