### ISSUE TITLE
Handling of wrapped scripts

### ISSUE THREAD

**Issue by reno-xjb** [matejak/argbash#35]
Hi,

I'm working on a bash framework using argbash, so first I'd like to thank you for this generator.

That said, I have a question and/or a request.

I'm using a lot the wrapping functionality, so lately I tried to something fancy to see if it was working : 

`# ARGBASH_WRAP([directory/stem])`

I was pleased to see that it doesn't make the generator fail, but sadly the output is not working.

I was wondering if wrapping with the relative path of the stem is something you have or would consider or is it really not a question (and so, shouldn't the generator failed) ?

I should precise that I know of the `--search` option and I use it, but in this precise case it is more of an organisation convenience as I provide a framework.

**Comment by matejak** [comment]
Hello, could you try again with the current `master`? I think that it should work.

**Comment by reno-xjb** [comment]
@matejak Yes it's working and it's great ! Thank you

**Comment by reno-xjb** [comment]
I was a little too enthusiast, it is working yes, but it is only missing the description of wrapped options in the help now

**Comment by matejak** [comment]
I am sorry, but I have misled you. The fix was part of the `wrap-improv` branch, not hhe `master`. However, I have just merged it to the `master`, so it should really work now.
