### ISSUE TITLE
Quoting issue with repeated optional args

### ISSUE THREAD

**Issue by reno-xjb** [matejak/argbash#41]
Hi,

I'm often using the ARG_OPTIONAL_REPEATED macro with a default value being a variable.
For example:
`# ARG_OPTIONAL_REPEATED([test],[t],[this is a test],["${my_array[@]}"])`

I put the quotes around my array in order to preserve spaces in its values.

Hence, the `_arg_test` variable is well set but in the help message, quotes are escaped, resulting in a weird display of my default values with quotes around as if they were only one long string.

Have you any idea how to deal with that ?

**Comment by matejak** [comment]
Hello Renaud,
I am happy to see your case. I have few questions"

1. Where is `my_array` defined? Is it at the beginning of the script before the declarations?
1. Could you please paste what you get as a help message?
1. How would you imagine an ideal help message?

I am sure that we will work towards an innovative solution.

**Comment by matejak** [comment]
Thank you for your clarification!
To be on the same page, I think that you typically don't want to do `_arg_test=(${my_array[@]})`. Watch this:
```
arr=(one "two three")
arr2=(${arr[@]})
arr3=("${arr[@]}")
echo "${arr[1]} --- ${arr2[1]} --- ${arr3[1]}"
> two three --- two --- two three
```
I think that if Argbash double-quoting the default in the assignment is OK. Do you have some specific use-case for the opposite?

I see that the help message needs some treatment.
I am thinking of:
```
printf '\t%s' "-t,--test: this is a test (default array:"
printf "' '%s'" <default goes here>
printf ')\n'
```
This would handle arrays well.
An alternative approach would be to detect `[@]` and subsitute `[*]` for the help message, but that help message would make the arrays `(one "two three")` and `(one two three)` look the same.

So I am inclined to ensure that the default is assigned double quoted and I am inclined to make the help message look like `    -t,--test: this is a test (default array: 'one' 'two three')`

Do you have any feedback or objections?

**Comment by reno-xjb** [comment]
Double-quoting the default in the assignment is indeed what's best for me. 
But I'm not sure it fits the general case, i.e. when default is not a variable: `# ARG_OPTIONAL_REPEATED([test],[t],[this is a test],[one "two three"])`. 
Here, if default is double quoted, it gives `_arg_test=("one "two three"")` (which is equivalent to `_arg_test=("one two" three)`, and not to what we want, i.e. `_arg_test=(one "two three")`).

For the help message, it is good. You just made a typo, it's  `printf " '%s'" <default goes here>` on the second line. However, the default must be double-quoted if it's a variable or it will be the same problem as for the assignment.

**Comment by matejak** [comment]
Great, I see your point. Therefore, it would be best for Argbash not to quote anything and emphasize how to properly quote the defaults on the input.

**Comment by matejak** [comment]
Could you please try the current master? I believe that I have fixed it and I hope that I haven't brought some some nasty regression :-)

**Comment by reno-xjb** [comment]
It seems to work well, that's great !

And I have to say that I really like this approach to keep the double-quoting to the user-side as it is more clear and less an hidden mechanism, so all good :)

**Comment by reno-xjb** [comment]
Just a small detail, you misplaced the parenthesis in the help message, so instead of 
`printf '\t%s' "-t, --test: this is a test (default array:"`
it is 
`printf '\t%s' "-t, --test: this is a test default array: ("`

Was it intentional ?

**Comment by matejak** [comment]
You are right, it was partially intentional and partially omission, but I think that now I have managed to come up with a great compromise.

**Comment by reno-xjb** [comment]
Indeed, that's great !
