### ISSUE TITLE
Wrapping wrapped scripts

### ISSUE THREAD

**Issue by reno-xjb** [matejak/argbash#42]
Could it be possible to wrap scripts which are already wrapping other scripts?

It doesn't seem to work for the moment.

**Comment by matejak** [comment]
Hello, thank you for your input. I will look into it; however, could you please share a use case for this feature? It might be quite interesting to e.g. include it in the documentation.

**Comment by reno-xjb** [comment]
In my case, I'm writing scripts on top of aws cli.

Hence, i'm wrapping common options like profile or region to avoid the duplication of option declaration, and i create some utility scripts (for creating a stack, consuming streams,...)

But it is still low level, and i sometimes would like to  create more complex scripts using those utility scripts, so wrapping these scripts options wrapping itself the common options.

In brief:
high-level script ---{wraps}---> low-level utility ---{wraps}---> common option

I don't know if it's clear enough, but I expect so

**Comment by matejak** [comment]
Hello, I am pretty sure that the issue is fixed in the current ``master``. Could you please confirm that?

**Comment by reno-xjb** [comment]
Yes it is working now, thank you !
