### ISSUE TITLE
Booleans have yes/no as default values and on/off as given values

### ISSUE THREAD

**Issue by martin-ueding** [matejak/argbash#47]
Perhaps I am just doing wrong, but it seems inconsistent to me. The default value for a boolean is `yes` or `no`:

```bash
_arg_verbose=yes
_arg_download_only=no
```

But when the user supplies this argument, it is set to `on` or `off`:

```bash
_arg_download_only="on"
 test "${1:0:5}" = "--no-" && _arg_download_only="off"
```

This means that I have to check for both variants in order to get it right consistently. This can't be the intention, right?

**Comment by martin-ueding** [comment]
Oh, it is my fault. I have specified `yes` and `no` as the default values, though I must specify `on` and `off`. Perhaps a check would be nice such that for boolean options only `on` and `off` are allowed as defaults.

**Comment by matejak** [comment]
Great point, the defaults guard is present in the current master.
