### ISSUE TITLE
confused about mandatory options

### ISSUE THREAD

**Issue by simbo1905** [matejak/argbash#56]
All my arguments are mandatory. I am confused about how to specify mandatory options so that I don't have to write logic to check all my args are passed.

**Comment by matejak** [comment]
Hello, mandatory options are not supported by Argbash. I don't know your use case, but if you insist on required arguments, use positional arguments.
Required arguments with options are supported by [some libraries](https://docs.python.org/3/library/argparse.html#required), but they are generally considered bad practice, as this is not compliant neither with POSIX nor GNU CLI standards.

**Comment by simbo1905** [comment]
That makes sense to me. I will go with the standards. Thanks!
