### ISSUE TITLE
Required named arguments?

### ISSUE THREAD

**Issue by gdevenyi** [matejak/argbash#64]
I don't see in the API a way to define a required named argument. If that is indeed not the case, I would like to request such an option.

Thanks!

**Comment by matejak** [comment]
This is a duplicate of #56.
You can implement the "required" part in your code, i.e. if the respective value is empty, raise an error. However, this functionality would violate POSIX/GNU command-line interface standards.

**Comment by gdevenyi** [comment]
Ah, I wasn't aware of that violating the command-line standards, I'd rather maintain those. Thanks.
