### ISSUE TITLE
License of code generated by ARGBASH

### ISSUE THREAD

**Issue by stephenmoloney** [matejak/argbash#66]
Hi, 

This is great tool

I just want to know about the license of the files generated by argbash. 

May I choose the license I want for the generated code (Eg Apache 2.0) or is the generated code
supposed to have the [BSD-3-Clause](https://github.com/matejak/argbash/blob/3bf413dfc41c7520e615097751aa8137b7ab358c/LICENSE) license ?

**Comment by matejak** [comment]
This is an interesting question. The intention of Argbash is to let it's users choose the license of the generated code - i.e. to work the same way as other content generators s.a. the `gcc` compiler or `gimp` image editor.
However, this should be clarified in a FAQ, as the generated code contains part of Argbash source code.
