### ISSUE TITLE
Update online generator to latest version

### ISSUE THREAD

**Issue by stephenmoloney** [matejak/argbash#68]
I could be mistaken but I think the online generator is at version 2.6.1

It would be great if it was updated to 2.8.1 or even better if there was a toggle selection option.

https://argbash.io/generate

**Comment by matejak** [comment]
Noted, although changes in argbash in recent minor versions were not so relevant for the online backend so much, as it doesn't do man pages/bash completion.

**Comment by stephenmoloney** [comment]
thanks - i'll close this issue !
