### ISSUE TITLE
Unmatched close square bracket in string causes many problems

### ISSUE THREAD

**Issue by KenYN** [matejak/argbash#70]
This fails in the offline version too. Go to [the generator](https://argbash.io/generate) and use this code for example:

```
# [ <-- needed because of Argbash

# Update window title escape code
echo -ne "\033]0;My new title\007"

if [ ! -z "$_arg_option" ]; then
    echo "Value of --option: $_arg_option"
fi

# ] <-- needed because of Argbash
```

Press the `GENERATE SCRIPT NOW` and:

```
### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

echo -ne "\0330;OK\007"

if !  -z "$_arg_option" ; then
    echo "Value of --option: $_arg_option"
fi
echo "print is $_arg_print"
echo "Value of positional-arg: $_arg_positional_arg"

# ] <-- needed because of Argbash
# ] <-- needed because of Argbash

```
Oops, all the square brackets have been stripped!

**Comment by matejak** [comment]
I understand your pain - luckily, square bracket matching issues is the only price that needs to be paid for using Argbash. On the bright side, it is a documented known issue, and there is a workaround: https://argbash.readthedocs.io/en/latest/#limitations
Does this adress your question?

**Comment by KenYN** [comment]
Thank you, a dummy comment on the previous line:

    # [

Works to keep the problem away. I didn't notice that documentation before...
