### ISSUE TITLE
Usage message should reflect when a set of accepted values is restricted.

### ISSUE THREAD

**Issue by hemna** [matejak/argbash#76]
Is there a way to provide a list of valid positional values?

I want my script to accept a single positional argument <command> where the command has a specific list of valid commands that it accepts?  Say the list is: start, stop, deploy, remove
if a user tries to enter a command such as 'foo' then the help comes up and says the command is not a valid command, here is the list and each command's description and help.

./my_script.sh <command>

./my_script.sh deploy
./my_script.sh stop
./my_script.sh start

./my_script.sh foo
this one fails and says that foo isn't a valid command, and provides a list of valid commands to pass and their help (description).

**Comment by matejak** [comment]
Take a look at [argbash guide](https://argbash.readthedocs.io/en/latest/guide.html#typing-macros), and check out the `ARG_TYPE_GROUP_SET` macro.

**Comment by hemna** [comment]
ok so I'm trying to do this.

```
#!/bin/bash

validcommands="deploy_ses,deploy_caasp,deploy_ccp_deployer"
Field_Separator=$IFS
cmds=""
IFS=,
for cmd in $validcommands; do
  cmds+="$cmd ";
done
IFS=$Field_Separator
commandshelp="The allowed commands are $cmds"


# m4_ignore(
echo "This is just a parsing library template, not the library - pass the parent script 'ass.m4' to 'argbash' to fix this." >&2
exit 11  #)Created by argbash-init v2.8.0
# ARG_POSITIONAL_SINGLE([command], [$commandshelp])
# ARG_TYPE_GROUP_SET([commands], [COMMAND], [command], [$validcommands], [index])
# ARG_DEFAULTS_POS
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO
```

```
┌─[waboring@walt-dev2] - [~/tmp] - [Wed Apr 10, 23:09]
└─[$] <> argbash -o test ass.m4
The --library option is deprecated, use --strip user-content next time
┌─[waboring@walt-dev2] - [~/tmp] - [Wed Apr 10, 23:09]
└─[$] <> ./test -h
<The general help message of my script>
Usage: ./test [-h|--help] <command>
	<command>: The allowed commands are deploy_ses deploy_caasp deploy_ccp_deployer
	-h, --help: Prints help
┌─[waboring@walt-dev2] - [~/tmp] - [Wed Apr 10, 23:09]
└─[$] <> ./test deploy_ses
Value 'deploy_ses' (of argument 'command') doesn't match the list of allowed values: 'deploy_ses,deploy_caasp,deploy_ccp_deployer'
```

**Comment by hemna** [comment]
since argbash doesn't show the list of valid options in help, I have to try a workaround.  
Unforunately it doesn't work either.   It shows the help that I'd like, but since the option is a var $validcommands, argbash doesn't seem to be able to recognize the input on the cmdln is valid.

**Comment by hemna** [comment]
If I change the declaration to 

```
# m4_ignore(
echo "This is just a parsing library template, not the library - pass the parent script 'ass.m4' to 'argbash' to fix this." >&2
exit 11  #)Created by argbash-init v2.8.0
# ARG_POSITIONAL_SINGLE([command], [$commandshelp])
# ARG_TYPE_GROUP_SET([commands], [COMMAND], [command], [deploy_ses,deploy_ass], [index])
# ARG_DEFAULTS_POS
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO
```
It works, but then I have to redeclare the same options multiple times (one for building the help text, and again to show the valid options).

```
┌─[waboring@walt-dev2] - [~/tmp] - [Wed Apr 10, 23:15]
└─[$] <> ./test test
Value 'test' (of argument 'command') doesn't match the list of allowed values: 'deploy_ses' and 'deploy_ass'
```

**Comment by matejak** [comment]
Yes, you are doing it right. The code generator can't have access to bash variables, so you have to repeat it for the help message text.
It is true that the help message should indicate the set of possible values.
