### ISSUE TITLE
Leftover args bug

### ISSUE THREAD

**Issue by matejak** [matejak/argbash#8]
Argbash 2.4.0 fails on the following input:

```
#!/bin/bash
#
# This is a rather minimal example Argbash potential
# Example taken from http://argbash.readthedocs.io/en/stable/example.html
#
# ARG_POSITIONAL_SINGLE([command], [c], [optional argument help msg])
# ARG_OPTIONAL_BOOLEAN([verbose], , [if set, output will be verbose])

# ARG_VERSION([echo $0 v$VERSION])
# ARG_HELP([The general script's help msg])

# ARG_LEFTOVERS([define 1 or more input file; if ommited scripts can still act on different values of SLRUM_PROCID])
# ARGBASH_GO 
```
producing a false alarm about unknown number of positional args before defining leftover arguments.

**Comment by cmeesters** [comment]
Hi Matěj,

Just for your information: Any(!) placement of ARG_POSITIONAL_X instead of ARG_LEFTOVERS essentially triggers the same alarm ("... This is not supported, define arguments
that accept fixed number of values first.").

Cheers
Christian

**Comment by matejak** [comment]
I see now that this is not strictly an Argbash bug - the
`ARG_POSITIONAL_SINGLE([command], [c], [optional argument help msg])`
has help "c" and default value "optional argument help msg". You probably want to make `command` optional, or remove the `[c]` argument - see http://argbash.readthedocs.io/en/stable/guide.html#positional-arguments.
However, I can see that the error message could be more helpful, so I will close the issue when it is improved.

**Comment by matejak** [comment]
The git master now gives a better feedback:
`error: The number of expected positional arguments before 'leftovers' is unknown (because of argument 'command', which has a default). This is not supported, define arguments that accept fixed number of values first.`
