### ISSUE TITLE
Ability to self-compile a script

### ISSUE THREAD

**Issue by BourgondAries** [matejak/argbash#83]
Feature request for argbash to be able to recompile itself whilst keeping the m4 code intact, allowing the script to be compiled again if a change is made.

Example:
```
argbash --selfcompile scriptfile.sh
# Add an ARG_OPTIONAL_SINGLE([something], ...)
argbash --selfcompile scriptfile.sh
./scriptfile.sh --something "should work" 
```

This has two positive benefits: First, the script works on all systems since argbash is not a required dependency, second, we always have the arg code at hand so we can recompile it easily, and don't need to mess about with multiple files.

**Comment by BourgondAries** [comment]
Found a solution
`argbash file.sh -o file.sh`, works well enough.

**Comment by matejak** [comment]
Yes, this is the correct way to do this.
