### ISSUE TITLE
Required optionals (mandatory flags)

### ISSUE THREAD

**Issue by BourgondAries** [matejak/argbash#84]
I want some arguments to be flagged like `--something`, without being optional. How can this be done?

**Comment by matejak** [comment]
This is a duplicate of #56.

Required arguments with options are supported by [some libraries](https://docs.python.org/3/library/argparse.html#required). It won't be implemented in Argbash though, as it is against GNU and POSIX standards.
If you need this functionality, you caneither
* use positional arguments if you have required arguments, or
* handle empty options after the parsing is done.
