### ISSUE TITLE
Help interferes with "h" argument

### ISSUE THREAD

**Issue by vamichael** [matejak/argbash#92]
I want to have an argument like:

> `# ARG_OPTIONAL_SINGLE([host], [h], [optional argument help msg])`

But that interferes with the following, which also wants to use `-h`.

> `# ARG_HELP([The general script's help msg])`

Is there a way to make ARG_HELP only work with `--help` instead?

**Comment by matejak** [comment]
Future versions of Argbash could use `-?` instead of `-h`. However, `ARG_HELP` is basically a shorthand of `ARG_OPTIONAL_ACTION(..., ...,  [Prints help], [print_help])`
